### ISSUE TITLE
isRemote is very sensitive to false positives

### ISSUE THREAD

**Issue by ju5t** [SpamExperts/directadmin-addon#1]
https://github.com/SpamExperts/directadmin-addon/blob/fb2d7f9bd617da2f82005798a7c48a1a3739750c/lib/DirectAdmin_API.php#L72

Basing a decision on whether or not a dot is set at the end of a record and if it includes `$domain` is extremely sensitive to false positives. If a user has decided to move their e-mail and only change the A records, not the MX records, this plugin will happily destroy it all. If the e-mail is hosted elsewhere there's only one setting that matters and that can be found in CMD_API_DNS_MX?domain=<DOMAIN>.

If `internal` is set to yes all e-mail is handled by the server the domain is also hosted on. If it's set to no then you can be sure it's hosted elsewhere.

Unfortunately though DirectAdmin has only made this setting available to a user. As an admin user you don't have direct permissions to run this API call. The only way to get around that is to connect as the user who owns the domain and run the call as that user. You would have to create a different socket that uses set_login('admin|username', 'password'). That way you do have access to CMD_API_DNS_MX.

**Comment by ju5t** [comment]
It turns out there's an easier way. Instead of adjusting set_login you could simply append the query string with as_user as described here: https://www.directadmin.com/features.php?id=1437.

**Comment by ju5t** [comment]
@tonyandrewmeyer is there anything I could do to get this into a production release as quickly as possible?

**Comment by tonyandrewmeyer** [comment]
@for93t would you be able to take a look at this?

**Comment by for93t** [comment]
@tonyandrewmeyer, the changes are looking good and the updated logic works fine. Normally we would release the new package in our build day - next Tuesday in this case.

**Comment by ju5t** [comment]
Thanks for the update @for93t. I'll see if I can push the changes to our servers sooner as this is a blocking issue for us.

**Comment by ju5t** [comment]
It looks like this still needs the old check too, I'll add that back and submit a new merge request @for93t.

**Comment by ju5t** [comment]
@alexkiro why was this issue reopened? I've pushed a new merge request back in December that solved it.
