### ISSUE TITLE
Check compatibility with php7

### ISSUE THREAD

**Issue by alexkiro** [SpamExperts/directadmin-addon#11]
Would be good to tests and adjust anything in the direct admin addon against php7. Any issues found should be fixed here. 

This should still work with both php5 and php7.

**Comment by LaurentiuTeodorescu** [comment]
This is already working (tested) on PHP 5.4 And PHP 7.4 as per [documentation](https://documentation.n-able.com/spamexperts/userguide/Content/Integration/directadmin-addon.htm).
