### ISSUE TITLE
Error: No Connection. Please, setup connection details in "directadminapi.conf"

### ISSUE THREAD

**Issue by adaivan** [SpamExperts/directadmin-addon#12]
### Version information
DirectAdmin v.1.50.1
PHP version: 5.5.38
### Steps to replicate

 1.The client installed DA, with API  enabled with SSL. He set public IP address of server and admin credentials in file directadminapi.conf.new, packaged file as tar.gz and installed. 

### Actual result
He's getting an error: No Connection. Please, setup connection details in "directadminapi.conf". SSL certificate is self-signed - 

### Other notes
When he disables SSL ssl=0 in directadminapi.conf.new then it still doesn't work and error message is the same.

whmcs #526813

**Comment by alexkiro** [comment]
Looks like a connection issue. I suggest using localhost as the IP and/or setting secure to `0`. 


![](https://dev.spamexperts.com/sites/default/files/pictures/direct-admin-api-conf.jpg)
