### ISSUE TITLE
Privacy domain issue when 2 users have the same localpart username

### ISSUE THREAD

**Issue by ashleyse2016** [SpamExperts/directadmin-addon#14]
It appears when 2 users have the same beginning part of the username, the domain list shows the domain from the other user with the same first part of their username. This is a data/privacy issue.

### Version information

```
# cat available_version.txt 
4.0.1490694693
```

### Steps to replicate

 1. install addon
 2. Create reseller
 3. Create user `bob` and add domain example.com
 4. Create user `bobsfriend` and add domain example.net
 5. Login as `bob` 
 6. Click Professional Spam Filter
 7. Click domain list
 

### Actual result

Result shows the domain from `bob` and `bobsfriend` 
### Expected result

Only the domains from that user should be shown.

**Comment by Agoodfella** [comment]
The issue cannot be reproduced after following the steps in this ticket's description.

Fix verified.
