### ISSUE TITLE
Plugin issues on new servers

### ISSUE THREAD

**Issue by Jouwhost** [SpamExperts/directadmin-addon#18]
### Version information
Controlpanel	DirectAdmin (Custombuild) 1.53.4
PHP version	7.2.9
Addon version	4.0.1508925016

### Actual result
There are errors when deleting or creating a domainname. DNS records are not changed due to this error.
This is on a freshly installed Centos 7 server with Directadmin Custombuild.
I did not have these issues with older servers. These older servers all use PHP-FPM 5.6 as main PHP version insead of 7.2. 
Installing older addon versions onto this new server gives the same errors.
I installed a 2nd Centos server with Directadmin and got the same results. Exactly the same errors.

### Steps to replicate
* What i did:
1. New installation of Centos 7 + Directadmin Custombuild with PHP-FPM 7.2 + 5.6 with Nginx as proxy. Exim, Dovecot.
2. Installation and configuration of SpamExperts Spamfilter Directadmin-addon
3. Add new domain in any user. Error occurs here. Domain is not added to SpamExperts Spampanel. MX records are not changed to SpamExperts records which set in SpamExperts directadmin-addon.
4. Go to SpamExperts directadmin-addon as admin. Toggle protection for the newly added domain. Gives success and domain is added to SpamExperts Spampanel but MX records are not changed.
5. Delete domainname created in user. Error occurs here.

Errors on domain creation:
PHP Notice: 
Undefined variable: output in /usr/local/directadmin/plugins/spamexperts/lib/Configuration.php on line 55

PHP Notice:
Undefined variable: return in /usr/local/directadmin/plugins/spamexperts/lib/Configuration.php on line 55

PHP Warning: 
exec() has been disabled for security reasons in /usr/local/directadmin/plugins/spamexperts/lib/Configuration.php on line 55

PHP Notice: 
Undefined variable: output in /usr/local/directadmin/plugins/spamexperts/lib/Configuration.php on line 57

PHP Warning: 
implode(): Invalid arguments passed in /usr/local/directadmin/plugins/spamexperts/lib/Configuration.php on line 57

### Other notes
I enabled debug.
Only a prospamfilter_admin.log was created. Containing nothing generated when deleting or creating a domain name.
It did contain rules generated when protection is enabled for domain as Directadmin admin.

prospamfilter_admin.log below:

2018-09-26 23:08:23
Request login.antispamcloud.com/api/domain/exists/domain/xxxxx.com/format/json
HTTP 200
{"messages":{"error":["The domain 'xxxxx.com' does not belong to the admin 'email@adress.com'."]},"result":null}

2018-09-26 23:08:28
Request login.antispamcloud.com/api/domain/add/domain/xxxxx.com/destinations/["mail.xxxxx.com","relay.xxxxx.nl"]/format/json/
HTTP 200
{"messages":{"success":["'Email archiving' has been disabled for the domain 'xxxxx.com'","Email notifications for the domain 'xxxxx.com' changed to be sent from 'email@adress.com'","Domain timezone updated successfully","Administrator's contact email for the domain 'xxxxx.com' is changed to ''","Domain 'xxxxx.com' added"]},"result":null}

I hope this can be tested en solved, i gladly help where possible.
To me the issue seems related to PHP 7.2 and currently just not compatible.

**Comment by dbistriceanu** [comment]
@Jouwhost It looks like on your new server the addon was not installed properly. 
Please check the [installation steps from our knowledge base](https://kb.spamexperts.com/29941-integration/227828-directadmin-addon#installation-and-configuration), specifically:

> In order to proceed you should remove ‘exec’ from the disable_functions in your php.ini.

**Comment by Jouwhost** [comment]
@dbistriceanu Thanks for your reply.
I did alott of testing and got it all working.
I will post below what i did, for someone else find later.


**The problem got solved when:**
**-** Use PHP 5.6 as main version (1) and PHP 7.2 as 2nd version (2) and build PHP.
This version will not work on PHP 7.2.

**- *** Using default Directadmin ports. Using custom ports does not work (out of the box).


*****
Although you can set custom Directadmin ports in directadminapi.conf.new, this will not work.
The port 2222 is hard coded in 3 files.
When i change this code to my custom port, it will work fine on custom ports aswell.



The plugin works but i see alott of room for improvement. Hope this will come in new updates.

**Comment by dbistriceanu** [comment]
@Jouwhost The port should not be hardcoded. 2222 should be just the default and the addon should support using a custom port by simply changing that default in the addon config file, [as described in our knowledge base](https://kb.spamexperts.com/29941-integration/227828-directadmin-addon?from_search=26905849#installation-and-configuration), so if that's the case then this is indeed a bug.

**Comment by dbistriceanu** [comment]
@Jouwhost FWIW everything seemed to be working fine with PHP 7.2:

Controlpanel | DirectAdmin 1.54.1
-- | --
PHP version | 7.2.10
Addon version | 4.0.1538483297

@SpamExperts/qa Please also double-check there are no issue with PHP 7.2

**Comment by Jouwhost** [comment]
I think there must be some differences in our options.conf.
Whenever switch to php7.2 it does not work, switch back to 5.6 works perfect.

For now this is fine.
Will doe more testing when installing a new batch of servers.
