### ISSUE TITLE
__autoload is deprecated

### ISSUE THREAD

**Issue by ju5t** [SpamExperts/directadmin-addon#19]
### Version information

I must say I feel reluctant to open an issue here because it feels like SpamExperts has dropped the ball and doesn't do any development on this anymore.

This module is using __autoload which is deprecated for a while. It needs to be replaced with spl_autoload_register. This function has been deprecated for 3 (!!) years.

### Steps to replicate

Use the module.

### Actual result

Get a deprecation notice.

### Expected result

No notice.

**Comment by LaurentiuTeodorescu** [comment]
Fixed in https://github.com/SpamExperts/directadmin-addon/pull/30.
