### ISSUE TITLE
When will new release be built for DA 1.62?

### ISSUE THREAD

**Issue by NielsH** [SpamExperts/directadmin-addon#27]
Hello,

Since DA release 1.62 our SpamExperts plugin does not work properly.
I see that in https://github.com/SpamExperts/directadmin-addon/commit/f576d6b384630af9b71a351c5356e62d1134407f this is fixed by @LaurentiuTeodorescu - we tried this manually and it works.

However, normally we have an "Update" button in the DA plugin interface, but the new version is not yet available there.
Can we expect it to be available soon?

Thanks!

**Comment by LaurentiuTeodorescu** [comment]
Yes, a new version should be published soon.

**Comment by NielsH** [comment]
Thanks. That's good to know!
I guess nothing can be said regarding an ETA? Should we think in days, or weeks?

Thank you!

**Comment by LaurentiuTeodorescu** [comment]
New stable was [released](https://github.com/SpamExperts/directadmin-addon/releases/tag/v4.0.1631273182-stable). You should have the option to update in Direct Admin plugin manager interface.
