### ISSUE TITLE
Hide sensitive data like the admin user

### ISSUE THREAD

**Issue by ju5t** [SpamExperts/directadmin-addon#3]
If you check a domain for protection it may return the following error message:

> The domain 'domain.com' does not belong to the admin 'adminuser'

That gives away the admin user you're connecting with. It shouldn't.

**Comment by ju5t** [comment]
I'm confused. This one was solved too just as #1. Can you explain why this was opened again? What needs to be done?

**Comment by lorentina** [comment]
Verified the admin username is not exposed after the fix.
