### ISSUE TITLE
Add support for login keys in directadminapi.conf

### ISSUE THREAD

**Issue by alexkiro** [SpamExperts/directadmin-addon#6]
Our directadmin addon currently requires plain text passwords in the configuration file. We should add support for [login keys](https://www.directadmin.com/features.php?id=1298 ) for more secure access control.

#### Acceptance criteria

 - [ ] We should also still support passwords in the configuration file as not to break backwards compatibility
 - [ ] Everything else should work the same as before 

#### Other notes

 - We might consider deprecating the support for passwords at some point.

**Comment by for93t** [comment]
The [documentation](https://github.com/SpamExperts/directadmin-addon/tree/issue_6#using-directadmin-login-keys) on how to use Login Keys has been added.

**Comment by lorentina** [comment]
Verified.
