### ISSUE TITLE
PHP warnings when creating a new domain

### ISSUE THREAD

**Issue by ju5t** [SpamExperts/directadmin-addon#7]
```
PHP Warning: Missing argument 2 for DirectAdmin_API::getDomainsMxRecords(), 
called in /usr/local/directadmin/plugins/spamexperts/lib/SpamExperts_API.php on line 177 
and defined in /usr/local/directadmin/plugins/spamexperts/lib/DirectAdmin_API.php on line 50
```

This was introduced in b76bf7b9 by myself. I'll submit a merge request hopefully later today.

**Comment by ju5t** [comment]
`$api->protectDomains()` is called from `domain_create_post.php`. 

Though when I try to use `getAllDomains()` to fetch the username it doesn't return the domain that gets added. I wonder if this is a bug and if DirectAdmin hasn't finished processing it yet. 

The username isn't passed as an argument unfortunately so at this point I can only come up with a workaround by setting `$username = null` in `getDomainsMxRecords()` here: https://github.com/SpamExperts/directadmin-addon/blob/master/lib/DirectAdmin_API.php#L50

Any thoughts?

**Comment by lorentina** [comment]
Verified that setting `$username = null` resolves the PHP warning.
