### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by ju5t** [SpamExperts/directadmin-addon#8]
It looks like the recent changes still haven't been made available on your download page. Is there any particular reason for that? It currently means we have to make a release ourselves and I prefer not to.

**Comment by alexkiro** [comment]
Hello,

I've re-opened the recent changes from the issues to keep track of them until they make it in a new release, which should be available in April. 

For faster response time to your questions please contact the support team directly by sending an email to support@spamexperts.com. If you are using the SpamExperts services from a reseller and not from SpamExperts directly, you need to contact your provider. If they cannot assist, they need to contact the SpamExperts support team for you.

**Comment by ju5t** [comment]
@alexkiro it helps if you explain in those issues why they have been reopened. It's a little confusing right now and it looks like it needs more input from myself for example.

I'll send an e-mail next time.

**Comment by alexkiro** [comment]
> @alexkiro it helps if you explain in those issues why they have been reopened. It's a little confusing right now and it looks like it needs more input from myself for example.

We will keep them open for tracking purposes, until they are included in a new release. I don't think a any input is required, thanks a lot for all your contributions! :+1:
